import os
import sqlite3
import datetime
import boto3
from google import genai
from google.genai import types
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import Header

# ---------------- 配置区域 ----------------
S3_BUCKET_NAME = os.environ.get("S3_BUCKET_NAME")
S3_ACCESS_KEY_ID = os.environ.get("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.environ.get("S3_SECRET_ACCESS_KEY")
S3_ENDPOINT_URL = os.environ.get("S3_ENDPOINT_URL")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# 邮件配置 (根据你上一次的反馈，已修正为读取 EMAIL_FROM)
SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.qq.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", 465))
SMTP_USER = os.environ.get("EMAIL_FROM")      # <--- 修正: 对应 GitHub Secret EMAIL_FROM
SMTP_PASSWORD = os.environ.get("EMAIL_PASSWORD") # <--- 修正: 对应 GitHub Secret EMAIL_PASSWORD
EMAIL_TO = os.environ.get("EMAIL_TO")

# ---------------- 1. 从 R2 下载数据 ----------------
def download_db():
    beijing_time = datetime.datetime.utcnow() + datetime.timedelta(hours=8)
    date_str = beijing_time.strftime("%Y-%m-%d")
    file_key = f"news/{date_str}.db"
    local_filename = "daily_news.db"

    print(f"[{beijing_time.strftime('%H:%M')}] 正在从 R2 下载: {file_key}")

    s3 = boto3.client(
        's3',
        endpoint_url=S3_ENDPOINT_URL,
        aws_access_key_id=S3_ACCESS_KEY_ID,
        aws_secret_access_key=S3_SECRET_ACCESS_KEY
    )

    try:
        s3.download_file(S3_BUCKET_NAME, file_key, local_filename)
        print("数据库下载成功。")
        return local_filename
    except Exception as e:
        print(f"下载失败 (可能是今天尚未生成数据): {e}")
        return None

# ---------------- 2. 读取 SQLite 数据 ----------------
def extract_hot_news(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    try:
        cursor.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='news_items'")
        if cursor.fetchone()[0] == 0:
            print("错误：数据库中找不到 news_items 表")
            return ""

        query = """
        SELECT title, platform_id, MAX(crawl_count) as heat 
        FROM news_items 
        GROUP BY title 
        ORDER BY heat DESC 
        LIMIT 150
        """
        cursor.execute(query)
        rows = cursor.fetchall()
        
        if not rows:
            print("数据库中没有数据行。")
            return ""

        news_lines = []
        for row in rows:
            title = row[0]
            platform = row[1]
            if title and len(title) > 4:
                news_lines.append(f"[{platform}] {title}")
        
        print(f"成功提取 {len(news_lines)} 条高热度新闻。")
        return "\n".join(news_lines)

    except Exception as e:
        print(f"读取数据库失败: {e}")
        return ""
    finally:
        conn.close()

# ---------------- 3. Gemini AI 分析 (返回 内容+模型名) ----------------
def analyze_with_gemini(news_content):
    if not news_content:
        return None, None

    print("正在初始化 Gemini Client...")
    client = genai.Client(api_key=GEMINI_API_KEY)

    # 候选模型列表
    candidate_models = [
        'gemini-3-pro-preview',  # 最新实验版
        'gemini-2.5-pro',  
        'gemini-2.5-flash',     
        'gemini-2.5-flash-lite'  
    ]

    beijing_time = datetime.datetime.utcnow() + datetime.timedelta(hours=8)
    hour = beijing_time.hour
    
    if hour < 12:
        period_title = "早报"
        greeting = "新的一天，来看看昨夜今晨的热点。"
    elif hour < 18:
        period_title = "午间速览"
        greeting = "忙碌之余，为您梳理最新的网络动态。"
    else:
        period_title = "晚间回顾"
        greeting = "结束了一天的工作，为您总结今日全网焦点。"

    prompt = f"""
    你是一个专业的新闻主编。以下是今日全网热搜数据。
    请生成一份 HTML 格式的**{period_title}**邮件。

    ### 要求：
    1.  **筛选核心**：提炼 5-8 个最值得关注的事件。
    2.  **深度一句话**：对每个标题进行一句话的背景扩充或深度锐评。
    3.  **排版**：
        -   仅输出 HTML 代码（无markdown标记）。
        -   使用内联 CSS (Inline CSS)。
        -   风格：现代、简洁、卡片式。
        -   **不要**在HTML中生成“Generated by Gemini”字样，这由系统自动添加。

    ### 数据源：
    {news_content}
    """

    for model_name in candidate_models:
        print(f"正在尝试使用模型: {model_name} ...")
        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )
            print(f"模型 {model_name} 调用成功！")
            text = response.text
            text = text.replace("```html", "").replace("```", "").strip()
            
            # 返回 元组 (内容, 模型名)
            return text, model_name

        except Exception as e:
            print(f"模型 {model_name} 失败: {e}")
            if "404" in str(e) or "not found" in str(e).lower():
                continue
            continue

    return None, None

# ---------------- 4. 发送邮件 (自动添加模型页脚) ----------------
def send_email(html_content, model_name):
    if not SMTP_USER or not EMAIL_TO:
        print("未配置邮件环境变量，跳过发送。")
        return

    msg = MIMEMultipart()
    beijing_time = datetime.datetime.utcnow() + datetime.timedelta(hours=8)
    date_str = beijing_time.strftime("%m月%d日")
    hour = beijing_time.hour
    period = "晚间" if hour >= 18 else "午间"
    
    msg['Subject'] = Header(f"TrendRadar {date_str} {period} AI简报", 'utf-8')
    msg['From'] = SMTP_USER
    msg['To'] = EMAIL_TO

    # --- 注入模型信息页脚 ---
    footer_html = f"""
    <div style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #eee; text-align: center; font-size: 12px; color: #999; font-family: sans-serif;">
        AI Analysis generated by <strong>{model_name}</strong> • TrendRadar
    </div>
    """
    
    # 检查 AI 返回的是否包含 </body>，如果有则插入在前面，没有则直接追加
    if "</body>" in html_content:
        final_html = html_content.replace("</body>", f"{footer_html}</body>")
    else:
        final_html = html_content + footer_html

    msg.attach(MIMEText(final_html, 'html', 'utf-8'))

    try:
        server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT)
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_USER, [EMAIL_TO], msg.as_string())
        server.quit()
        print(f"邮件已成功发送至: {EMAIL_TO} (Model: {model_name})")
    except Exception as e:
        print(f"邮件发送失败: {e}")

# ---------------- 主程序 ----------------
if __name__ == "__main__":
    print("--- 开始执行 TrendRadar AI 总结 ---")
    db_file = download_db()
    
    if db_file:
        raw_news = extract_hot_news(db_file)
        if raw_news:
            # 获取内容和模型名
            html_report, used_model = analyze_with_gemini(raw_news)
            
            if html_report and used_model:
                send_email(html_report, used_model)
            else:
                print("跳过发送：AI 未返回内容。")
        else:
            print("跳过发送：未提取到有效新闻。")
        
        try:
            os.remove(db_file)
        except:
            pass
    else:
        print("跳过执行：无法下载数据库文件。")